let favLocations = ["Iraq", "England", "Usa", "London", "Saudiarab"];
let dupFavLocations1 = ["Iraq", "England", "Usa", "London", "Saudiarab"];
let dupFavLocations2 = ["Iraq", "England", "Usa", "London", "Saudiarab"];
console.log(`Original form: ${favLocations}`);
dupFavLocations1.sort();
console.log(`In Alphabetical order: "${dupFavLocations1}`);
console.log(`Original form: ${favLocations}`);
dupFavLocations2.sort();
dupFavLocations2.reverse();
console.log(`In reverse alphabetical order : "${dupFavLocations2}`);
console.log(`Original form: ${favLocations}`);
favLocations.reverse();
console.log(`Reverse form of original : "${favLocations}`);
favLocations.reverse();
console.log(`Back to original : "${favLocations}`);
favLocations.sort();
console.log(`In Alphabetical order: "${dupFavLocations1}`);
favLocations.reverse();
console.log(`In Reverse Alphabetical order: "${dupFavLocations1}`);
